export const LITE_QUALIFIED_PERFORMANCE_INTERACTIONS = Object.freeze([
  'screen-steady',
  'screen-navigation',
  'manage-open',
  'manage-close',
  'overlay-open',
  'overlay-close',
  'nested-detail-open',
  'nested-detail-close',
  'section-switch',
  'nested-scroll',
  'history-open',
  'finding-detail-open',
  'confirmation-render',
  'list-scroll',
  'progress-update',
  'toast-settle',
  'refresh-feedback',
] as const);
