CREATE TABLE IF NOT EXISTS release_runtime_projection (
    owner TEXT PRIMARY KEY,
    schema_version INTEGER NOT NULL DEFAULT 1,
    projection_revision INTEGER NOT NULL DEFAULT 0,
    operation_generation INTEGER NOT NULL DEFAULT 0,
    active_generation INTEGER NOT NULL DEFAULT 0,
    active_operation TEXT NOT NULL DEFAULT '',
    active_command_id TEXT NOT NULL DEFAULT '',
    lease_expires_epoch_ms INTEGER NOT NULL DEFAULT 0,
    worker_generation TEXT NOT NULL DEFAULT '',
    phase TEXT NOT NULL DEFAULT 'unknown',
    status TEXT NOT NULL DEFAULT 'degraded',
    current_tag TEXT NOT NULL DEFAULT 'unknown',
    latest_tag TEXT NOT NULL DEFAULT 'unknown',
    update_available INTEGER NOT NULL DEFAULT 0 CHECK (update_available IN (0, 1)),
    canonical_hash TEXT NOT NULL DEFAULT '',
    payload_json TEXT NOT NULL DEFAULT '{}',
    payload_bytes INTEGER NOT NULL DEFAULT 2,
    last_checked_at TEXT,
    last_success_at TEXT,
    last_failure_at TEXT,
    last_failure_code TEXT NOT NULL DEFAULT '',
    last_terminal_command_id TEXT NOT NULL DEFAULT '',
    last_terminal_status TEXT NOT NULL DEFAULT '',
    last_terminal_generation INTEGER NOT NULL DEFAULT 0,
    checks_started INTEGER NOT NULL DEFAULT 0,
    checks_completed INTEGER NOT NULL DEFAULT 0,
    applies_started INTEGER NOT NULL DEFAULT 0,
    applies_completed INTEGER NOT NULL DEFAULT 0,
    unchanged_results INTEGER NOT NULL DEFAULT 0,
    writes_skipped INTEGER NOT NULL DEFAULT 0,
    writes_committed INTEGER NOT NULL DEFAULT 0,
    coalesced_requests INTEGER NOT NULL DEFAULT 0,
    deduplicated_requests INTEGER NOT NULL DEFAULT 0,
    pressure_deferred INTEGER NOT NULL DEFAULT 0,
    deadline_exceeded INTEGER NOT NULL DEFAULT 0,
    stale_results_rejected INTEGER NOT NULL DEFAULT 0,
    subprocess_restarts INTEGER NOT NULL DEFAULT 0,
    subprocess_recycles INTEGER NOT NULL DEFAULT 0,
    last_subprocess_pid INTEGER NOT NULL DEFAULT 0,
    last_subprocess_exit_code INTEGER,
    last_cpu_ms REAL NOT NULL DEFAULT 0,
    last_wall_ms REAL NOT NULL DEFAULT 0,
    last_peak_rss_bytes INTEGER NOT NULL DEFAULT 0,
    last_bytes_read INTEGER NOT NULL DEFAULT 0,
    last_files_examined INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_at_epoch_ms INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_release_runtime_status_updated
    ON release_runtime_projection(status, updated_at_epoch_ms DESC);

CREATE INDEX IF NOT EXISTS idx_release_runtime_active_lease
    ON release_runtime_projection(active_generation, lease_expires_epoch_ms);
