import { assign, createMachine } from 'xstate';
import { acceptedReference, friendlyFlowError, isBackendReachable } from './liteFlowGuards.js';

export const liteRecoveryFlowMachine = createMachine({
  id: 'liteRecoveryFlow', initial: 'idle', context: { backendReachable: true, savedStateOnly: false, backupId: null, previewId: null, acceptedCommandId: null, failureReason: '' },
  states: {
    idle: { on: { CHECK_READINESS: 'checkingReadiness', BACKEND_STATE: { actions: 'setBackendState' } } },
    checkingReadiness: { on: { READY: 'ready', SAVED_STATE_ONLY: 'savedStateOnly', BLOCKED: { target: 'blocked', actions: 'setFailure' }, FAILED: { target: 'failed', actions: 'setFailure' } } },
    ready: { on: { REQUEST_BACKUP: { target: 'backupRequested', guard: 'backendReachable' }, REQUEST_VERIFY: { target: 'verifyRequested', guard: 'backendReachable' }, REQUEST_PREVIEW: { target: 'previewRequested', guard: 'backendReachable' }, REQUEST_RESTORE: { target: 'restoreConfirmationRequired', guard: 'backendReachable' }, SAVED_STATE_ONLY: 'savedStateOnly' } },
    backupRequested: { on: { ACCEPTED: { target: 'backupQueued', actions: 'setAccepted' }, FAILED: { target: 'failed', actions: 'setFailure' } } },
    backupQueued: { on: { RUNNING: 'backupRunning', DONE: { target: 'backupDone', actions: 'setAccepted' }, FAILED: { target: 'failed', actions: 'setFailure' } } },
    backupRunning: { on: { DONE: { target: 'backupDone', actions: 'setAccepted' }, FAILED: { target: 'failed', actions: 'setFailure' } } },
    backupDone: { on: { REQUEST_VERIFY: 'verifyRequested', REQUEST_PREVIEW: 'previewRequired', RESET: 'ready' } },
    verifyRequested: { on: { ACCEPTED: { target: 'verifyQueued', actions: 'setAccepted' }, FAILED: { target: 'failed', actions: 'setFailure' } } },
    verifyQueued: { on: { RUNNING: 'verifying', DONE: { target: 'verified', actions: 'setAccepted' }, FAILED: { target: 'failed', actions: 'setFailure' } } },
    verifying: { on: { DONE: { target: 'verified', actions: 'setAccepted' }, FAILED: { target: 'failed', actions: 'setFailure' } } },
    verified: { on: { REQUEST_PREVIEW: 'previewRequested', REQUEST_RESTORE: 'previewRequired', RESET: 'ready' } },
    previewRequested: { on: { ACCEPTED: { target: 'previewQueued', actions: 'setAccepted' }, FAILED: { target: 'failed', actions: 'setFailure' } } },
    previewQueued: { on: { DONE: { target: 'previewReady', actions: 'setAccepted' }, RUNNING: 'previewQueued', FAILED: { target: 'failed', actions: 'setFailure' } } },
    previewReady: { on: { REQUEST_RESTORE: 'restoreConfirmationRequired', RESET: 'ready' } },
    restoreConfirmationRequired: { on: { CONFIRM_RESTORE: 'restoreRequested', CANCEL: 'cancelled', MISSING_CONFIRMATION: 'confirmationMissing' } },
    restoreRequested: { on: { ACCEPTED: { target: 'restoreQueued', actions: 'setAccepted' }, FAILED: { target: 'failed', actions: 'setFailure' } } },
    restoreQueued: { on: { CHECKPOINT_CREATING: 'checkpointCreating', RUNNING: 'restoring', FAILED: { target: 'failed', actions: 'setFailure' } } },
    checkpointCreating: { on: { RUNNING: 'restoring', FAILED: { target: 'failed', actions: 'setFailure' } } },
    restoring: { on: { VALIDATING_HEALTH: 'validatingHealth', DONE: 'complete', FAILED: { target: 'failed', actions: 'setFailure' } } },
    validatingHealth: { on: { DONE: 'complete', FAILED: { target: 'failed', actions: 'setFailure' } } }, complete: { on: { RESET: 'ready' } },
    previewRequired: { on: { REQUEST_PREVIEW: 'previewRequested', RESET: 'ready' } }, verificationRequired: { on: { REQUEST_VERIFY: 'verifyRequested', RESET: 'ready' } }, explicitBackupRequired: { on: { RESET: 'ready' } }, confirmationMissing: { on: { REQUEST_RESTORE: 'restoreConfirmationRequired', RESET: 'ready' } }, restoreBlocked: { on: { REQUEST_PREVIEW: 'previewRequested', REQUEST_VERIFY: 'verifyRequested', RESET: 'ready' } }, savedStateOnly: { on: { RESET: 'idle', BACKEND_STATE: { target: 'ready', actions: 'setBackendState' } } }, backendUnreachable: { on: { RESET: 'idle' } }, blocked: { on: { RESET: 'ready' } }, failed: { on: { RETRY: 'ready', RESET: 'idle' } }, cancelled: { on: { RESET: 'ready' } },
  },
}, { guards: { backendReachable: ({ context }) => isBackendReachable(context) }, actions: { setBackendState: assign(({ context, event }) => ({ backendReachable: event.backendReachable ?? context.backendReachable, savedStateOnly: event.savedStateOnly ?? context.savedStateOnly, backupId: event.backupId ?? context.backupId, previewId: event.previewId ?? context.previewId })), setAccepted: assign(({ context, event }) => ({ acceptedCommandId: acceptedReference(event.payload || {}) || context.acceptedCommandId, backupId: event.payload?.backup_id || event.backupId || context.backupId, previewId: event.payload?.preview_id || event.previewId || context.previewId, failureReason: '' })), setFailure: assign(({ event }) => ({ failureReason: event.reason || friendlyFlowError(event.error, 'Recovery needs attention.') })) } });

export const liteRecoveryFlowLabels = { idle: 'Recovery ready', checkingReadiness: 'Checking readiness…', ready: 'Recovery ready', backupRequested: 'Getting ready', backupQueued: 'Backup queued', backupRunning: 'Working', backupDone: 'Backup saved', verifyRequested: 'Getting ready', verifyQueued: 'Verification queued', verifying: 'Checking', verified: 'Backup verified', previewRequested: 'Getting ready', previewQueued: 'Preview queued', previewReady: 'Preview ready', restoreConfirmationRequired: 'Confirmation required', restoreRequested: 'Getting ready', restoreQueued: 'Restore queued', checkpointCreating: 'Safe restore point', restoring: 'Working', validatingHealth: 'Health passed', complete: 'Done', savedStateOnly: 'Restore cannot continue from saved state only', previewRequired: 'Preview required', verificationRequired: 'Verification required', explicitBackupRequired: 'Choose a backup first', confirmationMissing: 'Confirmation required before restore', restoreBlocked: 'Restore blocked', blocked: 'Needs attention', failed: 'Needs attention', cancelled: 'Cancelled' };
export function recoveryFlowSteps(value) { const v = String(value || 'idle'); return [{ id: 'backup', label: 'Backup saved', state: v.includes('backup') && v !== 'backupDone' ? 'active' : ['backupDone','verifyRequested','verifyQueued','verifying','verified','previewRequested','previewQueued','previewReady','restoreConfirmationRequired','restoreRequested','restoreQueued','checkpointCreating','restoring','validatingHealth','complete'].includes(v) ? 'done' : 'waiting' }, { id: 'verify', label: 'Backup verified', state: ['verifyRequested','verifyQueued','verifying'].includes(v) ? 'active' : ['verified','previewRequested','previewQueued','previewReady','restoreConfirmationRequired','restoreRequested','restoreQueued','checkpointCreating','restoring','validatingHealth','complete'].includes(v) ? 'done' : 'waiting' }, { id: 'preview', label: 'Preview ready', state: ['previewRequested','previewQueued'].includes(v) ? 'active' : ['previewReady','restoreConfirmationRequired','restoreRequested','restoreQueued','checkpointCreating','restoring','validatingHealth','complete'].includes(v) ? 'done' : 'waiting' }, { id: 'restore', label: 'Restore protected', state: ['restoreConfirmationRequired','restoreRequested','restoreQueued','checkpointCreating','restoring','validatingHealth'].includes(v) ? 'active' : v === 'complete' ? 'done' : ['blocked','failed','restoreBlocked'].includes(v) ? 'failed' : 'waiting' }]; }
