import { useEffect, useMemo } from 'react';
import { useMachine } from '@xstate/react';
import { liteRecoveryFlowLabels, liteRecoveryFlowMachine, recoveryFlowSteps } from '../machines/liteRecoveryFlowMachine.js';
import { writeBlockedReason } from '../machines/liteFlowGuards.js';
export const LITE_RECOVERY_FLOW_USES_FASTAPI_ONLY = true;
export function useLiteRecoveryFlow({ recovery = {}, latestBackup = null, latestPreview = null, backendReachable = true, savedStateOnly = false } = {}) {
  const [snapshot, send] = useMachine(liteRecoveryFlowMachine); const value = String(snapshot.value || 'idle'); const writeBlocked = savedStateOnly || backendReachable === false; const blockedReason = writeBlockedReason({ backendReachable, savedStateOnly });
  useEffect(() => { send({ type: 'BACKEND_STATE', backendReachable, savedStateOnly, backupId: latestBackup?.backup_id, previewId: latestPreview?.preview_id, status: recovery?.status }); if (savedStateOnly) send({ type: 'SAVED_STATE_ONLY' }); }, [backendReachable, latestBackup?.backup_id, latestPreview?.preview_id, recovery?.status, savedStateOnly, send]);
  const canWrite = () => { if (writeBlocked) { send({ type: 'SAVED_STATE_ONLY' }); return { ok: false, reason: blockedReason || 'Reconnect to continue.' }; } return { ok: true }; };
  return useMemo(() => ({ value, label: liteRecoveryFlowLabels[value] || 'Recovery ready', steps: recoveryFlowSteps(value), writeBlocked, blockedReason, context: snapshot.context, requestBackup: () => { const c = canWrite(); if (c.ok) send({ type: 'REQUEST_BACKUP' }); return c; }, backupAccepted: (payload) => send({ type: 'ACCEPTED', payload }), backupDone: (payload) => send({ type: 'DONE', payload }), requestVerify: () => { const c = canWrite(); if (c.ok) send({ type: 'REQUEST_VERIFY' }); return c; }, verifyAccepted: (payload) => send({ type: 'ACCEPTED', payload }), verified: (payload) => send({ type: 'DONE', payload }), requestPreview: () => { const c = canWrite(); if (c.ok) send({ type: 'REQUEST_PREVIEW' }); return c; }, previewAccepted: (payload) => send({ type: 'ACCEPTED', payload }), previewReady: (payload) => send({ type: 'DONE', payload }), requestRestore: ({ verified = false, previewReady = false, explicitBackup = false } = {}) => { const c = canWrite(); if (!c.ok) return c; if (!explicitBackup) return { ok: false, reason: 'Choose an explicit backup before restore.' }; if (!verified) return { ok: false, reason: 'Verify the backup before restore.' }; if (!previewReady) return { ok: false, reason: 'Preview restore before making changes.' }; send({ type: 'REQUEST_RESTORE' }); return { ok: true }; }, confirmRestore: () => send({ type: 'CONFIRM_RESTORE' }), restoreAccepted: (payload) => send({ type: 'ACCEPTED', payload }), complete: (payload) => send({ type: 'DONE', payload }), fail: (error) => send({ type: 'FAILED', error }), cancel: () => send({ type: 'CANCEL' }), reset: () => send({ type: 'RESET' }) }), [blockedReason, snapshot.context, value, writeBlocked]);
}
