import { useEffect, useMemo } from 'react';
import { useMachine } from '@xstate/react';
import { liteSecurityCheckLabels, liteSecurityCheckMachine, securityCheckFlowSteps } from '../machines/liteSecurityCheckMachine.js';
import { writeBlockedReason } from '../machines/liteFlowGuards.js';
export const LITE_SECURITY_CHECK_FLOW_USES_FASTAPI_ONLY = true;
function timelineHas(security, key) { const timeline = Array.isArray(security?.execution_timeline) ? security.execution_timeline : []; return timeline.some((step) => String(step?.key || '').toLowerCase() === key && ['completed','done','running','active'].includes(String(step?.status || step?.state || '').toLowerCase())); }
export function useLiteSecurityCheckFlow({ security = {}, backendReachable = true, savedStateOnly = false } = {}) {
  const [snapshot, send] = useMachine(liteSecurityCheckMachine); const value = String(snapshot.value || 'idle'); const writeBlocked = savedStateOnly || backendReachable === false; const blockedReason = writeBlockedReason({ backendReachable, savedStateOnly }); const runStatus = String(security?.last_run?.status || security?.scan_progress?.status || security?.status || '').toLowerCase();
  useEffect(() => { send({ type: 'BACKEND_STATE', backendReachable, savedStateOnly, runId: security?.last_run?.run_id, status: runStatus }); if (savedStateOnly) send({ type: 'SAVED_STATE_ONLY' }); if (timelineHas(security, 'worker_picked_up')) send({ type: 'WORKER_PICKED_UP' }); if (timelineHas(security, 'lynis_host_check')) send({ type: 'LYNIS_RUNNING' }); if (timelineHas(security, 'trivy_dependency_secret_check')) send({ type: 'TRIVY_RUNNING' }); if (timelineHas(security, 'evidence_saved')) send({ type: 'EVIDENCE_SAVED' }); if (security?.last_run?.partial_results) send({ type: 'PARTIAL_RESULTS' }); if (['succeeded','success','healthy','completed'].includes(runStatus)) send({ type: 'COMPLETE' }); if (['degraded','review','needs_attention','partial'].includes(runStatus)) send({ type: 'NEEDS_ATTENTION' }); if (['failed','failure','error'].includes(runStatus)) send({ type: 'FAILED', reason: security?.summary || 'Safety check needs attention.' }); }, [backendReachable, runStatus, savedStateOnly, security, send]);
  return useMemo(() => ({ value, label: liteSecurityCheckLabels[value] || 'Run Safety Check', steps: securityCheckFlowSteps(value), writeBlocked, blockedReason, context: snapshot.context, requestRun: () => { if (writeBlocked) { send({ type: 'SAVED_STATE_ONLY' }); return { ok: false, reason: blockedReason || 'Reconnect to continue.' }; } send({ type: 'CHECK_READINESS' }); send({ type: 'RUN' }); return { ok: true }; }, accepted: (payload) => send({ type: 'ACCEPTED', payload }), fail: (error) => send({ type: 'FAILED', error }), cancel: () => send({ type: 'CANCEL' }), reset: () => send({ type: 'RESET' }) }), [blockedReason, send, snapshot.context, value, writeBlocked]);
}
