import { useEffect, useMemo } from 'react';
import { useMachine } from '@xstate/react';
import { addDeviceFlowSteps, liteAddDeviceMachine, liteAddDeviceStateLabels } from '../machines/liteAddDeviceMachine.js';
import { writeBlockedReason } from '../machines/liteFlowGuards.js';
export const LITE_ADD_DEVICE_FLOW_USES_FASTAPI_ONLY = true;
export function useLiteAddDeviceFlow({ devices = [], latestInvite = null, backendReachable = true, savedStateOnly = false, remoteAccessReady = true } = {}) {
  const [snapshot, send] = useMachine(liteAddDeviceMachine); const value = String(snapshot.value || 'idle'); const writeBlocked = savedStateOnly || backendReachable === false; const blockedReason = writeBlockedReason({ backendReachable, savedStateOnly }) || (!remoteAccessReady ? 'Remote access not ready.' : '');
  useEffect(() => { send({ type: 'CHANGE', backendReachable, savedStateOnly }); }, [backendReachable, savedStateOnly, send]);
  useEffect(() => { if (!latestInvite) return; const name = String(latestInvite.hostname || latestInvite.name || '').toLowerCase(); const found = devices.find((d) => name && String(d?.name || d?.hostname || '').toLowerCase() === name); if (!found) { if (['inviteReady','creatingInvite'].includes(value)) send({ type: 'WAIT_FOR_DEVICE' }); return; } const state = String(found.connection || found.status || '').toLowerCase(); send({ type: ['online','healthy','ready'].includes(state) ? 'DEVICE_ONLINE' : 'DEVICE_JOINED' }); }, [devices, latestInvite, send, value]);
  return useMemo(() => ({ value, label: liteAddDeviceStateLabels[value] || 'Add Device', steps: addDeviceFlowSteps(value), writeBlocked, blockedReason, context: snapshot.context, enterDevice: (deviceName, role) => send({ type: 'ENTER_DEVICE', deviceName, role, backendReachable, savedStateOnly }), validateName: (deviceName, role) => { const name = String(deviceName || '').trim(); send({ type: 'VALIDATE_NAME', deviceName: name, role, backendReachable, savedStateOnly }); if (!name) { send({ type: 'NAME_INVALID', reason: 'Enter a device name.' }); return { ok: false, reason: 'Enter a device name.' }; } if (/token|secret|password|api[_-]?key/i.test(name)) { send({ type: 'NAME_INVALID', reason: 'Choose a simple device name without secret-like words.' }); return { ok: false, reason: 'Choose a simple device name without secret-like words.' }; } if (writeBlocked) { send({ type: 'BACKEND_UNREACHABLE', reason: blockedReason || 'Reconnect to continue.' }); return { ok: false, reason: blockedReason || 'Reconnect to continue.' }; } send({ type: 'NAME_VALID' }); return { ok: true }; }, createInvite: () => send({ type: 'SUBMIT' }), inviteReady: (payload) => send({ type: 'INVITE_READY', payload, invite: payload?.invite }), queued: (payload) => send({ type: 'QUEUED', payload, invite: payload?.invite }), block: (reason) => send({ type: 'BLOCKED', reason }), fail: (error) => send({ type: 'FAILED', error }), reset: () => send({ type: 'RESET' }) }), [backendReachable, blockedReason, savedStateOnly, send, snapshot.context, value, writeBlocked]);
}
