import { useMemo } from 'react';
import { useMachine } from '@xstate/react';
import { APP_ACTION_SAFETY_RULES, appActionFlowSteps, liteAppActionFlowLabels, liteAppActionFlowMachine } from '../machines/liteAppActionFlowMachine.js';
import { writeBlockedReason } from '../machines/liteFlowGuards.js';
export const LITE_APP_ACTION_FLOW_USES_FASTAPI_ONLY = true;
export function useLiteAppActionFlow({ backendReachable = true, savedStateOnly = false } = {}) {
  const [snapshot, send] = useMachine(liteAppActionFlowMachine); const value = String(snapshot.value || 'idle'); const writeBlocked = savedStateOnly || backendReachable === false; const blockedReason = writeBlockedReason({ backendReachable, savedStateOnly });
  return useMemo(() => ({ value, label: liteAppActionFlowLabels[value] || 'Ready', steps: appActionFlowSteps(value), writeBlocked, blockedReason, context: snapshot.context, safetyRules: APP_ACTION_SAFETY_RULES[snapshot.context.actionId] || [], review: (action = {}) => { const actionId = action.actionId || action.id || action.action_id || ''; const confirmationRequired = Boolean(action.confirmationRequired || action.confirmation_required || action.destructive || actionId === 'remove_app'); send({ type: 'REVIEW', appId: action.appId || action.app_id || 'photoprism', actionId, actionLabel: action.label || action.actionLabel || actionId.replace(/_/g, ' '), risk: action.risk || 'low', destructive: Boolean(action.destructive), confirmationRequired, backendReachable, savedStateOnly, disabledReason: action.disabledReason || action.disabled_reason || '' }); if (writeBlocked) send({ type: 'BLOCKED', reason: blockedReason || 'Reconnect to continue.' }); else if (confirmationRequired) send({ type: 'NEEDS_CONFIRMATION' }); }, submit: (action = {}) => { if (writeBlocked) { send({ type: 'BLOCKED', reason: blockedReason || 'Reconnect to continue.' }); return { ok: false, reason: blockedReason || 'Reconnect to continue.' }; } const actionId = action.actionId || action.id || action.action_id || snapshot.context.actionId; const confirmationRequired = Boolean(action.confirmationRequired || action.confirmation_required || action.destructive || actionId === 'remove_app'); if (confirmationRequired && action.confirmed !== true) { send({ type: 'NEEDS_CONFIRMATION', actionId, confirmationRequired }); return { ok: false, reason: 'Confirmation required.' }; } send({ type: 'SUBMIT', actionId, confirmationRequired }); return { ok: true }; }, confirm: () => send({ type: 'CONFIRM' }), accepted: (payload) => send({ type: 'ACCEPTED', payload }), queued: (payload) => send({ type: 'QUEUED', payload }), running: () => send({ type: 'RUNNING' }), resultReady: (payload) => send({ type: 'RESULT_READY', payload }), detailsReady: () => send({ type: 'DETAILS_READY' }), complete: () => send({ type: 'COMPLETE' }), block: (reason) => send({ type: 'BLOCKED', reason }), fail: (error) => send({ type: 'FAILED', error }), cancel: () => send({ type: 'CANCEL' }), reset: () => send({ type: 'RESET' }) }), [backendReachable, blockedReason, savedStateOnly, send, snapshot.context, value, writeBlocked]);
}
