import React from 'react';
import { ClipboardCheck, Clock3, Copy, ShieldCheck } from 'lucide-react';
import { ProgressiveDisclosure, StandardList, StandardListItem, StatusBadge } from './ui.jsx';

export default function EvidenceReceipt({ receipt, simpleMode = false, className = '' }) {
  if (!receipt) return null;
  const autoApproved = String(receipt.status || '').toLowerCase() === 'auto_approved' || String(receipt.message || '').toLowerCase().includes('auto-approved') || String(receipt.message || '').toLowerCase().includes('auto approved');
  const auditStamped = autoApproved || ['succeeded', 'success', 'done'].includes(String(receipt.status || '').toLowerCase());
  const copyReceipt = async () => {
    try {
      await navigator.clipboard.writeText(JSON.stringify(receipt, null, 2));
    } catch {
      // Clipboard is best-effort only. The receipt remains visible in the UI.
    }
  };

  return (
    <section className={`evidence-receipt enterprise-evidence-reveal ${auditStamped ? 'audit-stamp-receipt' : ''} ${autoApproved ? 'auto-approval-receipt' : ''} ${className}`} aria-label={simpleMode ? 'Safety record' : 'Audit evidence receipt'}>
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex min-w-0 items-start gap-3">
          <div className="rounded-2xl border border-emerald-300/20 bg-emerald-500/10 p-2 text-emerald-100"><ClipboardCheck className="h-5 w-5" /></div>
          <div className="min-w-0">
            <p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-200/90">{simpleMode ? 'Safety record' : 'Evidence receipt'}</p>
            <h3 className="mt-1 break-words text-lg font-black text-white">{receipt.title}</h3>
            <p className="mt-1 text-sm leading-6 text-slate-300">{autoApproved ? (simpleMode ? 'Approved safely and audit recorded.' : 'Auto-approval completed and audit evidence was recorded.') : (simpleMode ? 'Pocket Lab saved a record for this action.' : 'This receipt summarizes the operation result and evidence generated by the control-plane flow.')}</p>
            {auditStamped ? <p className="audit-stamp-note">{simpleMode ? 'Evidence saved' : 'Audit evidence recorded'}</p> : null}
          </div>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <StatusBadge status={receipt.status} simpleMode={simpleMode} />
          <button type="button" onClick={copyReceipt} className="pocket-button pocket-button-secondary evidence-copy-ready"><Copy className="h-4 w-4" /> Copy</button>
        </div>
      </div>

      <div className="mt-4 grid gap-3 sm:grid-cols-3">
        <div className="receipt-fact"><span>Reference</span><strong>{receipt.jobId || receipt.id}</strong></div>
        <div className="receipt-fact"><span>Mode</span><strong>{receipt.mode}</strong></div>
        <div className="receipt-fact"><span>Completed</span><strong>{receipt.completedAt ? new Date(receipt.completedAt).toLocaleString() : 'In progress'}</strong></div>
      </div>

      <ProgressiveDisclosure simpleMode={simpleMode} title={simpleMode ? 'Show saved record details' : 'Show evidence details'} className="mt-4">
        <StandardList title={simpleMode ? 'Recorded evidence' : 'Evidence entries'}>
          {receipt.evidence.map((item) => (
            <StandardListItem
              key={item}
              className="enterprise-evidence-item"
              icon={ShieldCheck}
              title={item}
              description={simpleMode ? 'Saved as part of the Pocket Lab action record.' : 'Produced by the Control API / worker / event / audit control-plane path.'}
              status="succeeded"
              simpleMode={simpleMode}
              metadata={[{ label: 'Time', value: receipt.completedAt || receipt.startedAt }]}
            />
          ))}
          {receipt.message ? (
            <StandardListItem
              icon={Clock3}
              title={simpleMode ? 'Result message' : 'Operation result message'}
              description={receipt.message}
              status={receipt.status}
              simpleMode={simpleMode}
            />
          ) : null}
        </StandardList>
      </ProgressiveDisclosure>
    </section>
  );
}
