/*
 * Source-owned qualification map for the expensive nested Lite UI boundaries.
 * The matrix describes safe read/projection work only; it is not an operation
 * allow-list and must not be used to authorize backend mutations.
 */
export const LITE_UI_PERFORMANCE_MATRIX = Object.freeze([
  {
    screen: 'home',
    nestedSurface: 'Workspace details / Technical details',
    authorityRequired: 'read-only workspace projection',
    interaction: 'nested-detail-open',
    safeExecutionMode: 'mocked-safe-read; live/physical read-only',
    evidenceId: 'home.workspace-details.technical-details.open',
  },
  {
    screen: 'home',
    nestedSurface: 'Workspace details / Technical details',
    authorityRequired: 'read-only workspace projection',
    interaction: 'nested-detail-close',
    safeExecutionMode: 'mocked-safe-read; live/physical read-only',
    evidenceId: 'home.workspace-details.technical-details.close',
  },
  {
    screen: 'catalog',
    nestedSurface: 'PhotoPrism Manage / action sections',
    authorityRequired: 'app projection; synthetic owner authority only if live Owner-gated projection requires it',
    interaction: 'section-switch',
    safeExecutionMode: 'mocked-safe-read; live/physical read-only',
    evidenceId: 'catalog.photoprism-manage.section-switch',
  },
  {
    screen: 'catalog',
    nestedSurface: 'PhotoPrism Manage / action details',
    authorityRequired: 'app projection; synthetic owner authority only if live Owner-gated projection requires it',
    interaction: 'nested-detail-open',
    safeExecutionMode: 'mocked-safe-read; live/physical read-only',
    evidenceId: 'catalog.photoprism-action.details-open',
  },
  {
    screen: 'devices',
    nestedSurface: 'Device details / Diagnostics and history',
    authorityRequired: 'fleet read projection',
    interaction: 'nested-detail-open',
    safeExecutionMode: 'mocked-safe-read; live/physical read-only',
    evidenceId: 'devices.device-details.diagnostics-open',
  },
  {
    screen: 'devices',
    nestedSurface: 'Device details / health history',
    authorityRequired: 'fleet read projection',
    interaction: 'history-open',
    safeExecutionMode: 'mocked-safe-read; live/physical read-only',
    evidenceId: 'devices.device-details.health-history-open',
  },
  {
    screen: 'devices',
    nestedSurface: 'Device details / long detail surface',
    authorityRequired: 'fleet read projection',
    interaction: 'nested-scroll',
    safeExecutionMode: 'mocked-safe-read; live/physical read-only',
    evidenceId: 'devices.device-details.nested-scroll',
  },
  {
    screen: 'security',
    nestedSurface: 'Security Manage / history details',
    authorityRequired: 'security read projection',
    interaction: 'history-open',
    safeExecutionMode: 'mocked-safe-read; live/physical read-only',
    evidenceId: 'security.manage.history-open',
  },
  {
    screen: 'security',
    nestedSurface: 'Security Manage / finding details',
    authorityRequired: 'security read projection',
    interaction: 'finding-detail-open',
    safeExecutionMode: 'mocked-safe-read; live/physical read-only',
    evidenceId: 'security.manage.finding-details-open',
  },
  {
    screen: 'identity',
    nestedSurface: 'Manage access / protected confirmation presentation',
    authorityRequired: 'synthetic owner authority only for live Owner-gated projection',
    interaction: 'confirmation-render',
    safeExecutionMode: 'mocked-safe-render; live/physical confirmation is not submitted',
    evidenceId: 'identity.manage-access.confirmation-render',
  },
  {
    screen: 'rules',
    nestedSurface: 'Manage Safety Rules / Technical status',
    authorityRequired: 'rules read projection; synthetic owner authority only for live Owner-gated projection',
    interaction: 'nested-detail-open',
    safeExecutionMode: 'mocked-safe-read; live/physical read-only',
    evidenceId: 'rules.manage.technical-status-open',
  },
  {
    screen: 'recovery',
    nestedSurface: 'Manage recovery / section tabs',
    authorityRequired: 'recovery read projection',
    interaction: 'section-switch',
    safeExecutionMode: 'mocked-safe-read; live/physical read-only',
    evidenceId: 'recovery.manage.section-switch',
  },
  {
    screen: 'recovery',
    nestedSurface: 'Manage recovery / action details',
    authorityRequired: 'recovery read projection',
    interaction: 'nested-detail-open',
    safeExecutionMode: 'mocked-safe-read; live/physical read-only',
    evidenceId: 'recovery.manage.action-details-open',
  },
]);
